-- ============================================================
-- VetAnimal · Esquema de base de datos (PostgreSQL en Supabase)
-- Lo aplica el servidor al arrancar (db/init.ts). Todas las sentencias son
-- idempotentes, así que se puede ejecutar sobre una base que ya tiene las tablas.
-- RLS queda activado sin políticas: la API pública de Supabase (anon key) no puede
-- leer ni escribir nada; solo el servidor, que se conecta directo a Postgres.
-- ============================================================

DO $$ BEGIN CREATE TYPE rol_usuario AS ENUM ('cliente', 'veterinario'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE categoria_servicio AS ENUM ('general', 'especializado'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE estado_derivacion AS ENUM ('activa', 'presentada', 'completada', 'vencida'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE estado_turno AS ENUM ('pendiente', 'confirmado', 'cancelado', 'completado'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE tipo_consulta AS ENUM ('CONTROL', 'EMERGENCIA', 'VACUNA', 'CIRUGIA', 'DIAGNOSTICO'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE estado_pedido AS ENUM ('pendiente', 'pagado', 'enviado', 'entregado', 'cancelado'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE tipo_entrega AS ENUM ('retiro', 'envio'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS usuarios (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(120) NOT NULL,
  email         VARCHAR(190) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  rol           rol_usuario NOT NULL DEFAULT 'cliente',
  telefono      VARCHAR(40)  NOT NULL DEFAULT '',
  especialidad  VARCHAR(120),
  matricula     VARCHAR(40),
  foto          TEXT,
  creado_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_email ON usuarios (email);

CREATE TABLE IF NOT EXISTS mascotas (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id           INTEGER NOT NULL REFERENCES usuarios (id),
  nombre               VARCHAR(80) NOT NULL,
  especie              VARCHAR(40) NOT NULL,
  raza                 VARCHAR(80) NOT NULL DEFAULT '',
  edad                 NUMERIC(4,1),
  peso                 NUMERIC(5,2),
  foto                 TEXT,
  estado_salud         VARCHAR(60) NOT NULL DEFAULT 'Estable',
  alergias             TEXT,
  condiciones_cronicas TEXT,
  activo               BOOLEAN NOT NULL DEFAULT true,
  creado_en            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mascotas_usuario ON mascotas (usuario_id);

CREATE TABLE IF NOT EXISTS servicios (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                VARCHAR(120) NOT NULL,
  descripcion           TEXT,
  duracion_min          SMALLINT NOT NULL DEFAULT 30,
  precio                NUMERIC(10,2) NOT NULL DEFAULT 0,
  icono                 VARCHAR(40) NOT NULL DEFAULT '',
  categoria             categoria_servicio NOT NULL DEFAULT 'general',
  especialidad          VARCHAR(120),
  estudio_sugerido      VARCHAR(255),
  derivacion_habilitada BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS centros_derivacion (
  id                 VARCHAR(60) PRIMARY KEY,
  nombre             VARCHAR(160) NOT NULL,
  direccion          VARCHAR(200) NOT NULL,
  localidad          VARCHAR(120) NOT NULL,
  telefono           VARCHAR(40)  NOT NULL DEFAULT '',
  whatsapp           VARCHAR(40),
  horarios           VARCHAR(200) NOT NULL DEFAULT '',
  especialidades     JSONB NOT NULL DEFAULT '[]',
  equipamiento       JSONB NOT NULL DEFAULT '[]',
  medico_responsable VARCHAR(200) NOT NULL DEFAULT '',
  distancia_estimada VARCHAR(120) NOT NULL DEFAULT '',
  acepta_urgencias   BOOLEAN NOT NULL DEFAULT false,
  orden              SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS derivaciones (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo                VARCHAR(40) NOT NULL,
  mascota_id            INTEGER NOT NULL REFERENCES mascotas (id),
  veterinario_emisor_id INTEGER NOT NULL REFERENCES usuarios (id),
  centro_destino_id     VARCHAR(60) NOT NULL REFERENCES centros_derivacion (id),
  edad                  NUMERIC(4,1),
  peso                  NUMERIC(5,2),
  especialidad_derivada VARCHAR(120) NOT NULL,
  estudio_solicitado    VARCHAR(255) NOT NULL,
  motivo_derivacion     VARCHAR(500) NOT NULL,
  sospecha_diagnostica  TEXT NOT NULL,
  resumen_clinico       TEXT,
  indicaciones_previas  TEXT,
  fecha_emision         DATE NOT NULL,
  fecha_validez_hasta   DATE NOT NULL,
  estado                estado_derivacion NOT NULL DEFAULT 'activa',
  creado_en             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_derivaciones_codigo ON derivaciones (codigo);
CREATE INDEX IF NOT EXISTS idx_derivaciones_mascota ON derivaciones (mascota_id);

-- dia_semana: 0 = domingo … 6 = sábado.
CREATE TABLE IF NOT EXISTS horarios_veterinario (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  veterinario_id INTEGER NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
  dia_semana     SMALLINT NOT NULL,
  hora_inicio    TIME NOT NULL,
  hora_fin       TIME NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_horarios_veterinario ON horarios_veterinario (veterinario_id, dia_semana);

CREATE TABLE IF NOT EXISTS turnos (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mascota_id             INTEGER NOT NULL REFERENCES mascotas (id),
  servicio_id            INTEGER NOT NULL REFERENCES servicios (id),
  veterinario_id         INTEGER REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha                  DATE NOT NULL,
  hora                   TIME NOT NULL,
  duracion_min           SMALLINT NOT NULL DEFAULT 30,
  estado                 estado_turno NOT NULL DEFAULT 'confirmado',
  notas                  TEXT,
  es_especializado       BOOLEAN NOT NULL DEFAULT false,
  especialidad           VARCHAR(120),
  estudio_solicitado     VARCHAR(255),
  sintomas_observados    TEXT,
  tiene_estudios_previos BOOLEAN NOT NULL DEFAULT false,
  derivacion_id          INTEGER REFERENCES derivaciones (id) ON DELETE SET NULL,
  creado_en              TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Un veterinario no puede tener dos turnos activos que empiecen a la misma hora.
CREATE UNIQUE INDEX IF NOT EXISTS uq_turnos_horario ON turnos (veterinario_id, fecha, hora) WHERE estado <> 'cancelado';
CREATE INDEX IF NOT EXISTS idx_turnos_fecha ON turnos (fecha);
CREATE INDEX IF NOT EXISTS idx_turnos_mascota ON turnos (mascota_id);

CREATE TABLE IF NOT EXISTS consultas (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mascota_id     INTEGER NOT NULL REFERENCES mascotas (id),
  veterinario_id INTEGER REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha          DATE NOT NULL,
  tipo           tipo_consulta NOT NULL DEFAULT 'CONTROL',
  titulo         VARCHAR(200) NOT NULL,
  descripcion    TEXT NOT NULL,
  creado_en      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_consultas_mascota ON consultas (mascota_id);

CREATE TABLE IF NOT EXISTS vacunas (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mascota_id       INTEGER NOT NULL REFERENCES mascotas (id),
  nombre           VARCHAR(120) NOT NULL,
  fecha_aplicacion DATE,
  fecha_refuerzo   DATE
);
CREATE INDEX IF NOT EXISTS idx_vacunas_mascota ON vacunas (mascota_id);

CREATE TABLE IF NOT EXISTS estudios (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mascota_id         INTEGER NOT NULL REFERENCES mascotas (id),
  nombre             VARCHAR(200) NOT NULL,
  tipo               VARCHAR(60)  NOT NULL DEFAULT 'Radiografía',
  fecha              DATE NOT NULL,
  zona_anatomica     VARCHAR(160),
  imagen_url         TEXT,
  observaciones      TEXT,
  veterinario_id     INTEGER REFERENCES usuarios (id) ON DELETE SET NULL,
  veterinario_nombre VARCHAR(160),
  institucion        VARCHAR(200),
  resultado_url      VARCHAR(500) NOT NULL DEFAULT '#'
);
CREATE INDEX IF NOT EXISTS idx_estudios_mascota ON estudios (mascota_id);

CREATE TABLE IF NOT EXISTS productos (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          VARCHAR(200) NOT NULL,
  categoria       VARCHAR(60)  NOT NULL DEFAULT 'Medicamentos',
  etiqueta        VARCHAR(60)  NOT NULL DEFAULT '',
  descripcion     TEXT,
  precio          NUMERIC(10,2) NOT NULL,
  requiere_receta BOOLEAN NOT NULL DEFAULT false,
  stock           INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  imagen          TEXT
);

CREATE TABLE IF NOT EXISTS pedidos (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
  usuario_id        INTEGER NOT NULL REFERENCES usuarios (id),
  total             NUMERIC(10,2) NOT NULL,
  estado            estado_pedido NOT NULL DEFAULT 'pendiente',
  entrega           tipo_entrega NOT NULL DEFAULT 'retiro',
  direccion_envio   VARCHAR(255),
  telefono_contacto VARCHAR(40),
  creado_en         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pedidos_usuario ON pedidos (usuario_id);

CREATE TABLE IF NOT EXISTS pedido_items (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id       INTEGER NOT NULL REFERENCES pedidos (id) ON DELETE CASCADE,
  producto_id     INTEGER REFERENCES productos (id) ON DELETE SET NULL,
  cantidad        INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(10,2) NOT NULL,
  producto_nombre VARCHAR(200) NOT NULL,
  producto_imagen TEXT,
  requiere_receta BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_pedido_items_pedido ON pedido_items (pedido_id);

CREATE TABLE IF NOT EXISTS sesiones (
  token_hash CHAR(64) PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
  expira_en  TIMESTAMPTZ NOT NULL,
  creado_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sesiones_usuario ON sesiones (usuario_id);

CREATE TABLE IF NOT EXISTS recuperaciones_password (
  token_hash CHAR(64) PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
  expira_en  TIMESTAMPTZ NOT NULL,
  usado      BOOLEAN NOT NULL DEFAULT false,
  creado_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_recuperaciones_usuario ON recuperaciones_password (usuario_id);

CREATE TABLE IF NOT EXISTS operativos_moviles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo      VARCHAR(160) NOT NULL,
  organizador VARCHAR(160) NOT NULL DEFAULT '',
  servicios   VARCHAR(255) NOT NULL,
  fecha       DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin    TIME NOT NULL,
  direccion   VARCHAR(200) NOT NULL,
  localidad   VARCHAR(120) NOT NULL,
  latitud     NUMERIC(9,6) NOT NULL,
  longitud    NUMERIC(9,6) NOT NULL,
  requisitos  TEXT,
  creado_en   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_operativos_fecha ON operativos_moviles (fecha);

CREATE TABLE IF NOT EXISTS avisos_operativos (
  usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
  localidad  VARCHAR(120) NOT NULL,
  PRIMARY KEY (usuario_id, localidad)
);
CREATE INDEX IF NOT EXISTS idx_avisos_localidad ON avisos_operativos (localidad);

CREATE TABLE IF NOT EXISTS pagos (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id        INTEGER NOT NULL REFERENCES pedidos (id) ON DELETE CASCADE,
  proveedor        VARCHAR(40) NOT NULL DEFAULT 'simulado',
  referencia       VARCHAR(40) NOT NULL,
  monto            NUMERIC(10,2) NOT NULL,
  cuotas           SMALLINT NOT NULL DEFAULT 1,
  tarjeta_marca    VARCHAR(30) NOT NULL,
  tarjeta_ultimos4 CHAR(4) NOT NULL,
  titular          VARCHAR(120) NOT NULL,
  creado_en        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pagos_pedido ON pagos (pedido_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pagos_referencia ON pagos (referencia);

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE mascotas ENABLE ROW LEVEL SECURITY;
ALTER TABLE servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE centros_derivacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE derivaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE horarios_veterinario ENABLE ROW LEVEL SECURITY;
ALTER TABLE turnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultas ENABLE ROW LEVEL SECURITY;
ALTER TABLE vacunas ENABLE ROW LEVEL SECURITY;
ALTER TABLE estudios ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedido_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE sesiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE recuperaciones_password ENABLE ROW LEVEL SECURITY;
ALTER TABLE operativos_moviles ENABLE ROW LEVEL SECURITY;
ALTER TABLE avisos_operativos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagos ENABLE ROW LEVEL SECURITY;
