// Datos iniciales de demostración de VetAnimal.
// Los carga el servidor al arrancar (db/init.ts) cuando la base está vacía y no hay un data_storage.json para importar.

export const users = [
  {
    id: 1,
    nombre: "Dr. Santiago Méndez (Admin)",
    email: "admin@vetanimal.com",
    password: "Admin2026!",
    rol: "veterinario" as const,
    telefono: "11-6426-0688",
    especialidad: "Medicina General y Cirugía",
    matricula: "MP 14.280",
    foto: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&q=80",
  },
  {
    id: 2,
    nombre: "Dra. Martina Paz",
    email: "martina.paz@vetanimal.com",
    password: "123456",
    rol: "veterinario" as const,
    telefono: "11-4000-1001",
    especialidad: "Emergencias y Cuidados Críticos",
    matricula: "MP 17.519",
    foto: "https://images.unsplash.com/photo-1594824813566-78809a712f5a?w=200&q=80",
  },
  {
    id: 3,
    nombre: "Agustina Gómez",
    email: "agustina.gomez@example.com",
    password: "123456",
    rol: "cliente" as const,
    telefono: "11-5555-2222",
    especialidad: null,
    foto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80",
  },
  {
    id: 4,
    nombre: "Carlos Bianchi",
    email: "carlos.bianchi@example.com",
    password: "123456",
    rol: "cliente" as const,
    telefono: "11-4433-2211",
    especialidad: null,
    foto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
  {
    id: 5,
    nombre: "Valeria Rossi",
    email: "valeria.rossi@example.com",
    password: "123456",
    rol: "cliente" as const,
    telefono: "11-6677-8899",
    especialidad: null,
    foto: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
  },
];

export const pets = [
  {
    id: 1,
    usuario_id: 3,
    nombre: "Bella",
    especie: "Perro",
    raza: "Golden Retriever",
    edad: 4,
    peso: 28.5,
    foto: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=500&q=80",
    estado_salud: "Estable",
    alergias: "Picaduras de Pulga, Polen",
    condiciones_cronicas: "Ninguna diagnosticada a la fecha.",
    creado_en: "2024-01-10 10:00:00",
  },
  {
    id: 2,
    usuario_id: 3,
    nombre: "Milo",
    especie: "Gato",
    raza: "Siamés / Pelo Corto",
    edad: 3,
    peso: 4.2,
    foto: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&q=80",
    estado_salud: "Estable",
    alergias: "Ninguna",
    condiciones_cronicas: "Control preventivo de vías urinarias.",
    creado_en: "2024-03-15 14:30:00",
  },
  {
    id: 3,
    usuario_id: 3,
    nombre: "Luna",
    especie: "Gato",
    raza: "Mestiza Carey / Tricolor",
    edad: 2,
    peso: 3.6,
    foto: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=500&q=80",
    estado_salud: "Estable",
    alergias: "Sensibilidad a pescados comerciales",
    condiciones_cronicas: "Esterilizada. Vacunación completa.",
    creado_en: "2024-06-20 09:15:00",
  },
  {
    id: 4,
    usuario_id: 4,
    nombre: "Simba",
    especie: "Gato",
    raza: "Europeo Atigrado Naranja",
    edad: 1,
    peso: 4.0,
    foto: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=500&q=80",
    estado_salud: "Estable",
    alergias: "Ninguna",
    condiciones_cronicas: "Plan de vacunación inicial completado.",
    creado_en: "2025-01-12 11:20:00",
  },
  {
    id: 5,
    usuario_id: 4,
    nombre: "Rocky",
    especie: "Perro",
    raza: "Boxer",
    edad: 5,
    peso: 31.0,
    foto: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=500&q=80",
    estado_salud: "En tratamiento",
    alergias: "Ninguna",
    condiciones_cronicas: "Soplo sistólico en seguimiento. Derivado a Tortuguitas para ecocardiograma doppler.",
    creado_en: "2023-11-05 16:40:00",
  },
  {
    id: 6,
    usuario_id: 5,
    nombre: "Oliver",
    especie: "Gato",
    raza: "British Shorthair Gris",
    edad: 4,
    peso: 5.2,
    foto: "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=500&q=80",
    estado_salud: "Estable",
    alergias: "Ninguna",
    condiciones_cronicas: "Profilaxis y limpieza dental programada.",
    creado_en: "2024-02-18 10:00:00",
  },
];

export const services = [
  {
    id: 1,
    nombre: "Chequeo General",
    descripcion: "Consulta médica preventiva estándar de 30 minutos",
    duracion_min: 30,
    precio: 25.0,
    icono: "heart",
    categoria: "general" as const,
  },
  {
    id: 2,
    nombre: "Cirugía Avanzada",
    descripcion: "Salas quirúrgicas con bloque extendido y monitoreo multiparamétrico",
    duracion_min: 90,
    precio: 250.0,
    icono: "scalpel",
    categoria: "general" as const,
  },
  {
    id: 3,
    nombre: "Diagnósticos de Laboratorio",
    descripcion: "Análisis clínicos bioquímicos, hemogramas y sedimentos",
    duracion_min: 45,
    precio: 60.0,
    icono: "flask",
    categoria: "general" as const,
  },
  {
    id: 4,
    nombre: "Vacunación & Desparasitación",
    descripcion: "Aplicación de vacunas quíntuple, séxtuple y antirrábica oficial",
    duracion_min: 20,
    precio: 18.0,
    icono: "syringe",
    categoria: "general" as const,
  },
  // Servicios Especializados de Alta Complejidad e Interconsultas
  {
    id: 5,
    nombre: "Cardiografía & Ecocardiograma Doppler",
    descripcion: "Estudio cardiológico completo, ECG de 12 derivaciones y Doppler color. Sujeto a derivación e interconsulta especializada.",
    duracion_min: 45,
    precio: 85.0,
    icono: "heart-pulse",
    categoria: "especializado" as const,
    especialidad: "Cardiología",
    estudio_sugerido: "Cardiografía / Ecocardiograma Doppler Color + Electrocardiograma de 12 derivaciones",
    derivacion_habilitada: true,
  },
  {
    id: 6,
    nombre: "Radiología Digital de Alta Frecuencia",
    descripcion: "Placas radiológicas HD contrastadas con informe médico oficial y visor negatoscopio digital.",
    duracion_min: 40,
    precio: 70.0,
    icono: "scan",
    categoria: "especializado" as const,
    especialidad: "Radiología / Diagnóstico por Imágenes",
    estudio_sugerido: "Radiografía Digital de Tórax / Columna / Miembros en Alta Resolución",
    derivacion_habilitada: true,
  },
  {
    id: 7,
    nombre: "Ecografía Doppler Abdominal & Vascular",
    descripcion: "Evaluación ecográfica especializada de parénquima de órganos internos y flujos hemodinámicos.",
    duracion_min: 40,
    precio: 75.0,
    icono: "activity",
    categoria: "especializado" as const,
    especialidad: "Ecografía Doppler",
    estudio_sugerido: "Ecografía Abdominal Completa con Mapeo Doppler Vascular",
    derivacion_habilitada: true,
  },
  {
    id: 8,
    nombre: "Traumatología & Ortopedia Quirúrgica",
    descripcion: "Interconsulta ortopédica, análisis dinámico de marcha, articulaciones y lesiones ligamentarias.",
    duracion_min: 50,
    precio: 90.0,
    icono: "bone",
    categoria: "especializado" as const,
    especialidad: "Traumatología Compleja",
    estudio_sugerido: "Evaluación traumatológica especializada con estudios radiológicos dinámicos",
    derivacion_habilitada: true,
  },
];

type TurnoEstado = 'pendiente' | 'confirmado' | 'cancelado' | 'completado';

interface TurnoItem {
  id: number;
  mascota_id: number;
  servicio_id: number;
  veterinario_id: number;
  fecha: string;
  hora: string;
  estado: TurnoEstado;
  notas: string;
  creado_en: string;
  es_especializado?: boolean;
  categoria_servicio?: 'general' | 'especializado';
  especialidad?: string;
  estudio_solicitado?: string;
  sintomas_observados?: string;
  tiene_estudios_previos?: boolean;
  derivado?: boolean;
  derivacion_id?: number;
  derivacion_codigo?: string;
}

export const turnos: TurnoItem[] = [
  {
    id: 1,
    mascota_id: 1,
    servicio_id: 1,
    veterinario_id: 1,
    fecha: "2026-08-15",
    hora: "10:00",
    estado: "confirmado",
    notas: "Consulta de rutina preventiva.",
    creado_en: "2026-08-01 12:00:00",
    es_especializado: false,
    categoria_servicio: "general",
    derivado: false,
  },
  {
    id: 2,
    mascota_id: 1,
    servicio_id: 4,
    veterinario_id: 2,
    fecha: "2026-08-20",
    hora: "11:30",
    estado: "confirmado",
    notas: "Refuerzo anual.",
    creado_en: "2026-08-05 14:30:00",
    es_especializado: false,
    categoria_servicio: "general",
    derivado: false,
  },
  {
    id: 3,
    mascota_id: 1,
    servicio_id: 5,
    veterinario_id: 1,
    fecha: "2026-09-18",
    hora: "10:30",
    estado: "confirmado",
    notas: "Sospecha de soplo sistólico, fatiga tras ejercicio ligero.",
    creado_en: "2026-09-02 11:00:00",
    es_especializado: true,
    categoria_servicio: "especializado",
    especialidad: "Cardiología",
    estudio_solicitado: "Cardiografía / Ecocardiograma Doppler Color + ECG",
    sintomas_observados: "Tos nocturna intermitente, jadeo excesivo en reposo.",
    tiene_estudios_previos: false,
    derivado: false,
  },
];

export const consultas = [
  {
    id: 1,
    mascota_id: 1,
    veterinario_id: 1,
    fecha: "2024-05-15",
    tipo: "CONTROL" as const,
    titulo: "Control Anual Preventivo",
    descripcion:
      "Paciente presenta excelente condición física. Se realizó examen físico completo, limpieza dental superficial y actualización de peso.",
    creado_en: "2024-05-15 11:00:00",
  },
  {
    id: 2,
    mascota_id: 1,
    veterinario_id: 2,
    fecha: "2024-03-02",
    tipo: "EMERGENCIA" as const,
    titulo: "Urgencia: Dermatitis Aguda",
    descripcion:
      "Reacción alérgica en zona abdominal. Se administró antihistamínico vía oral y se recetó pomada calmante por 7 días.",
    creado_en: "2024-03-02 16:20:00",
  },
  {
    id: 3,
    mascota_id: 1,
    veterinario_id: 1,
    fecha: "2023-11-20",
    tipo: "VACUNA" as const,
    titulo: "Vacunación Cuádruple",
    descripcion:
      "Aplicación de refuerzo anual sin complicaciones posteriores.",
    creado_en: "2023-11-20 10:15:00",
  },
];

export const vacunas = [
  {
    id: 1,
    mascota_id: 1,
    nombre: "Antirrábica",
    fecha_aplicacion: "2025-05-15",
    fecha_refuerzo: "2026-05-15",
    estado: "AL_DIA" as const,
  },
  {
    id: 2,
    mascota_id: 1,
    nombre: "DHPP (Quíntuple)",
    fecha_aplicacion: "2025-11-20",
    fecha_refuerzo: "2026-11-20",
    estado: "AL_DIA" as const,
  },
  {
    id: 3,
    mascota_id: 1,
    nombre: "Giardia",
    fecha_aplicacion: "2023-04-10",
    fecha_refuerzo: "2024-04-10",
    estado: "VENCIDA" as const,
  },
];

export const estudios = [
  {
    id: 1,
    mascota_id: 1,
    nombre: "Radiografía Digital Torácica (VD y Lat)",
    tipo: "Radiografía",
    fecha: "2026-08-15",
    zona_anatomica: "Tórax Frente y Perfil",
    imagen_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=900&q=80",
    observaciones: "Evaluación cardiotorácica. Silueta cardíaca dentro de límites normales (Índice vertebral de Buchanan 9.5v). Parénquima pulmonar sin infiltrados alveolares ni efusión pleural.",
    veterinario_id: 1,
    veterinario_nombre: "Dr. Santiago Méndez (MP 14.280)",
    institucion: "VetAnimal - Servicio de Radiología Digital",
    resultado_url: "#",
  },
  {
    id: 2,
    mascota_id: 1,
    nombre: "Radiografía de Cadera & Pelvis (VD)",
    tipo: "Radiografía",
    fecha: "2026-06-10",
    zona_anatomica: "Pelvis Ventrodorsal con Miembros Extendidos",
    imagen_url: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=900&q=80",
    observaciones: "Estudio de articulaciones coxofemorales. Buena profundidad acetabular bilateral, sin remodelación ósea degenerativa ni osteofitos periacetabulares activos.",
    veterinario_id: 2,
    veterinario_nombre: "Dra. Martina Paz (MP 17.519)",
    institucion: "VetAnimal - Servicio de Radiología Digital",
    resultado_url: "#",
  },
  {
    id: 3,
    mascota_id: 1,
    nombre: "Ecocardiograma Doppler Color",
    tipo: "Cardiología / ECG",
    fecha: "2026-05-02",
    zona_anatomica: "Región Cardíaca",
    imagen_url: "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=900&q=80",
    observaciones: "Interconsulta externa especializada. Flujo transvalvular laminar, ritmo regular sin ectopias. Fracción de acortamiento ventricular 35% (normofuncional).",
    veterinario_id: 1,
    veterinario_nombre: "Dra. Silvina Morales (MP 8.940)",
    institucion: "Centro Veterinario Tortuguitas (Cura Brochero 1420)",
    resultado_url: "#",
  },
  {
    id: 4,
    mascota_id: 1,
    nombre: "Hemograma y Bioquímica Completa",
    tipo: "Laboratorio",
    fecha: "2026-07-20",
    zona_anatomica: "Muestra Sanguínea",
    imagen_url: "",
    observaciones: "Recuento leucocitario normal. Función renal y hepática en valores basales normales. Apto para intervenciones programadas.",
    veterinario_id: 1,
    veterinario_nombre: "Dr. Santiago Méndez (MP 14.280)",
    institucion: "VetAnimal - Laboratorio Central",
    resultado_url: "#",
  },
];

export const centrosDerivacion = [
  {
    id: "tortuguitas-brochero",
    nombre: "Centro Veterinario & Diagnóstico Tortuguitas",
    direccion: "Calle Cura Brochero 1420 (e/ Moreno y Las Araucarias)",
    localidad: "Tortuguitas, Gran Buenos Aires",
    telefono: "(02320) 49-2210",
    whatsapp: "+54 9 11 5566-7788",
    horarios: "Lunes a Sábados 08:30 a 20:00 hs (Guardia de emergencias 24 hs)",
    especialidades: [
      "Cardiología Veterinaria & Electrocardiografía",
      "Ecocardiograma Doppler Color",
      "Radiología Digital de Alta Frecuencia",
      "Cirugía de Alta Complejidad",
    ],
    equipamiento: [
      "Ecocardiograma Doppler Color Mindray Z60",
      "Equipo de Rayos X Digital Sedecal 500mA",
      "Monitor Multiparamétrico y Electrocardiógrafo Bistos",
      "Quirófano Especializado con Anestesia Inhalatoria",
    ],
    medico_responsable: "Dra. Silvina Morales (Cardióloga e Imagenóloga Veterinaria, MP 8.940)",
    distancia_estimada: "12 minutos desde VetAnimal Del Viso",
    acepta_urgencias: true,
  },
  {
    id: "hospital-pilar",
    nombre: "Hospital Veterinario de Alta Complejidad Pilar",
    direccion: "Colectora Panamericana Ramal Pilar Km 50.5",
    localidad: "Pilar, Gran Buenos Aires",
    telefono: "(0230) 464-5500",
    whatsapp: "+54 9 11 3322-1100",
    horarios: "Atención Continua 24 Horas / 365 días",
    especialidades: [
      "Tomografía Computada Multicorte (TAC)",
      "Traumatología y Ortopedia Compleja",
      "Unidad de Terapia Intensiva (UTI)",
      "Cirugía Neurológica",
    ],
    equipamiento: [
      "Tomógrafo Multicorte Siemens Somatom",
      "Quirófano Traumatológico con Arco en C Radioscópico",
      "Laboratorio de Gases y Electrolitos en Sangre",
    ],
    medico_responsable: "Dr. Gustavo Albarracín (Director Quirúrgico, MP 11.204)",
    distancia_estimada: "15 minutos desde VetAnimal Del Viso",
    acepta_urgencias: true,
  },
  {
    id: "diagnostico-delviso",
    nombre: "Laboratorio y Centro Integral Del Viso",
    direccion: "Av. Madero (Ruta 26) 1280",
    localidad: "Del Viso, Gran Buenos Aires",
    telefono: "(02320) 47-1122",
    whatsapp: "+54 9 11 4455-9988",
    horarios: "Lunes a Viernes 08:00 a 19:00 hs · Sábados 08:30 a 14:00 hs",
    especialidades: [
      "Bioquímica Clínica Completa",
      "Citología y Anatomía Patológica",
      "Perfiles Hormonales e Inmunodiagnóstico",
    ],
    equipamiento: [
      "Analizador Automático de Química Clínica",
      "Contador Hematológico Láser Veterinario",
    ],
    medico_responsable: "Dra. Romina Carballo (Bioquímica Veterinaria, MP 6.312)",
    distancia_estimada: "5 minutos (Centro Del Viso)",
    acepta_urgencias: false,
  },
];

export const derivaciones = [
  {
    id: 1,
    codigo: "ORD-2026-TORT-0081",
    mascota_id: 1,
    mascota_nombre: "Rocky",
    especie: "Perro",
    raza: "Golden Retriever",
    edad: 4,
    peso: 28.5,
    dueno_nombre: "Agustina Gómez",
    dueno_telefono: "11-5555-2222",
    dueno_email: "agustina.gomez@example.com",
    veterinario_emisor_id: 1,
    veterinario_emisor_nombre: "Dr. Santiago Méndez",
    veterinario_matricula: "MP 14.280",
    clinica_origen: "VetAnimal - Sede Del Viso / Pilar",
    centro_destino: centrosDerivacion[0],
    especialidad_derivada: "Cardiología" as const,
    estudio_solicitado: "Cardiografía / Ecocardiograma Doppler Color + Electrocardiograma",
    motivo_derivacion: "Falta de especialista cardiólogo en sede" as const,
    sospecha_diagnostica: "Soplo sistólico grado III/VI en foco mitral en auscultación periódica. Se solicita valoración cardiológica para evaluar regurgitación mitral y descartar cardiopatía estructural antes de programar cirugía.",
    resumen_clinico: "Canino normotenso, activo, sin episodios sincopales ni disnea en reposo. No recibe inotrópicos ni IECA actualmente.",
    indicaciones_previas: "Ayuno de 6 horas de sólidos. Presentar esta orden oficial emitida por VetAnimal en recepción del Centro Veterinario Tortuguitas en Calle Cura Brochero 1420.",
    fecha_emision: "2026-08-20",
    fecha_validez_hasta: "2026-09-20",
    estado: "activa" as const,
    creado_en: "2026-08-20 11:30:00",
  },
  {
    id: 2,
    codigo: "ORD-2026-TORT-0082",
    mascota_id: 1,
    mascota_nombre: "Rocky",
    especie: "Perro",
    raza: "Golden Retriever",
    edad: 4,
    peso: 28.5,
    dueno_nombre: "Agustina Gómez",
    dueno_telefono: "11-5555-2222",
    dueno_email: "agustina.gomez@example.com",
    veterinario_emisor_id: 2,
    veterinario_emisor_nombre: "Dra. Martina Paz",
    veterinario_matricula: "MP 17.519",
    clinica_origen: "VetAnimal - Sede Del Viso / Pilar",
    centro_destino: centrosDerivacion[0],
    especialidad_derivada: "Radiología / Diagnóstico por Imágenes" as const,
    estudio_solicitado: "Radiografía Digital de Columna Lumbo-Sacra y Pelvis (VD y Lateral)",
    motivo_derivacion: "Saturación de turnos / derivación prioritaria" as const,
    sospecha_diagnostica: "Claudicación en miembro posterior derecho posterior a esfuerzo físico. Descartar espondilosis o displasia coxofemoral.",
    resumen_clinico: "Molestia leve a la extensión pasiva de articulación de cadera derecha. Reflejos espinales normales.",
    indicaciones_previas: "Ayuno de 8 horas de sólidos ante eventual sedación para posicionamiento radiológico de precisión.",
    fecha_emision: "2026-08-28",
    fecha_validez_hasta: "2026-09-28",
    estado: "activa" as const,
    creado_en: "2026-08-28 16:45:00",
  },
];

export const products = [
  {
    id: 1,
    nombre: "Royal Canin Mini Adult (Bolsa 7.5 kg)",
    categoria: "Nutrición y Alimento" as const,
    etiqueta: "PREMIUM",
    descripcion:
      "Alimento completo y balanceado para perros adultos de razas pequeñas. Enriquecido con EPA/DHA.",
    precio: 48.5,
    requiere_receta: false,
    stock: 35,
    imagen: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&q=80",
  },
  {
    id: 2,
    nombre: "Champú Medicado Clorhexidina & Ketoconazol (250 ml)",
    categoria: "Bienestar y Estética" as const,
    etiqueta: "DERMATOLOGÍA",
    descripcion:
      "Champú antiséptico y antifúngico para el tratamiento de dermatitis bacterianas y fúngicas en caninos y felinos.",
    precio: 19.8,
    requiere_receta: false,
    stock: 50,
    imagen: "https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=400&q=80",
  },
  {
    id: 3,
    nombre: "Champú Hipoalergénico de Avena & Aloe Vera (500 ml)",
    categoria: "Bienestar y Estética" as const,
    etiqueta: "PIEL SENSIBLE",
    descripcion:
      "Fórmula ultra suave con pH neutro. Hidrata y calma la piel con prurito sin irritar los ojos.",
    precio: 15.5,
    requiere_receta: false,
    stock: 45,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
  },
  {
    id: 4,
    nombre: "Pro Plan Puppy Cachorro OptiStart (Bolsa 15 kg)",
    categoria: "Nutrición y Alimento" as const,
    etiqueta: "CACHORROS",
    descripcion:
      "Nutrición avanzada con calostro materno para fortalecer el sistema inmunológico y el desarrollo óseo.",
    precio: 82.0,
    requiere_receta: false,
    stock: 20,
    imagen: "https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=400&q=80",
  },
  {
    id: 5,
    nombre: "Hills Prescription Diet Metabolic Gatos (Bolsa 3 kg)",
    categoria: "Nutrición y Alimento" as const,
    etiqueta: "RECETADO",
    descripcion:
      "Alimento clínico especializado para el control de peso y soporte articular en felinos.",
    precio: 44.0,
    requiere_receta: true,
    stock: 18,
    imagen: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&q=80",
  },
  {
    id: 6,
    nombre: "Bravecto Comprimido Masticable (10 a 20 kg)",
    categoria: "Pulgas y Garrapatas" as const,
    etiqueta: "PROTECCIÓN 12 SEMANAS",
    descripcion:
      "Tratamiento y prevención sistémica de infestaciones por pulgas y garrapatas durante 3 meses completos.",
    precio: 36.9,
    requiere_receta: false,
    stock: 60,
    imagen: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&q=80",
  },
  {
    id: 7,
    nombre: "NexGard Spectra Antiparasitario Completo (3.5 a 7.5 kg)",
    categoria: "Pulgas y Garrapatas" as const,
    etiqueta: "PROTECCIÓN TOTAL",
    descripcion:
      "Tableta masticable sabor carne. Protege contra pulgas, garrapatas, sarna y parásitos intestinales.",
    precio: 31.5,
    requiere_receta: false,
    stock: 40,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
  },
  {
    id: 8,
    nombre: "Condroprotector Articular con Colágeno & Glucosamina (90 comp.)",
    categoria: "Medicamentos" as const,
    etiqueta: "SUPLEMENTO",
    descripcion:
      "Fórmula articular para perros mayores o con displasia de cadera. Estimula la regeneración del cartílago.",
    precio: 29.9,
    requiere_receta: false,
    stock: 30,
    imagen: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80",
  },
];

// Operativos de ejemplo de veterinarias móviles. `en_dias` indica cuántos días
// después de la carga cae cada uno, así siempre aparecen como próximos.
export const operativosMoviles = [
  {
    titulo: "Quirófano móvil de castración",
    organizador: "Programa municipal de zoonosis (dato de ejemplo)",
    servicios: "Castración gratuita de perros y gatos",
    en_dias: 4,
    hora_inicio: "08:00",
    hora_fin: "13:00",
    direccion: "Plaza central de Del Viso",
    localidad: "Del Viso",
    latitud: -34.4502,
    longitud: -58.7968,
    requisitos:
      "Ayuno de 12 horas de sólidos y 6 de agua. Perros con collar y correa, gatos en transportadora o bolso cerrado. Llevar una manta y el DNI.",
  },
  {
    titulo: "Jornada de vacunación antirrábica",
    organizador: "Programa municipal de zoonosis (dato de ejemplo)",
    servicios: "Vacunación antirrábica gratuita y desparasitación",
    en_dias: 9,
    hora_inicio: "10:00",
    hora_fin: "15:00",
    direccion: "Plaza 12 de Octubre",
    localidad: "Pilar",
    latitud: -34.4587,
    longitud: -58.9139,
    requisitos: "Animales mayores de 3 meses. Se atiende por orden de llegada.",
  },
  {
    titulo: "Veterinaria móvil: castración y vacunación",
    organizador: "Programa municipal de zoonosis (dato de ejemplo)",
    servicios: "Castración con turno previo y vacunación antirrábica",
    en_dias: 16,
    hora_inicio: "09:00",
    hora_fin: "14:00",
    direccion: "Sociedad de fomento del barrio, frente a la estación",
    localidad: "Tortuguitas",
    latitud: -34.4706,
    longitud: -58.7561,
    requisitos: "Ayuno de 12 horas para castración. Los turnos se entregan en el lugar desde las 8:30.",
  },
];
